name: Deploy Angular to GitHub Pages

on:
  push:
    branches: [ main ]   # change if your default branch isn't "main"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - run: npm ci

      # Build with correct base href:
      # For a user/organization site repo named <username>.github.io, change base-href to "/"
      - run: npm run build -- --configuration=production --base-href=/${{ github.event.repository.name }}/

      # Find the folder that contains index.html (Angular outputs to dist/<app>/browser/)
      - name: Find build directory and add 404.html for SPA routing
        id: prep
        shell: bash
        run: |
          set -e
          INDEX_PATH=$(find dist -maxdepth 4 -type f -name index.html -print -quit)
          if [ -z "$INDEX_PATH" ]; then
            echo "index.html not found under dist/"
            exit 1
          fi
          BUILD_DIR=$(dirname "$INDEX_PATH")
          cp "$BUILD_DIR/index.html" "$BUILD_DIR/404.html"
          echo "build_dir=$BUILD_DIR" >> "$GITHUB_OUTPUT"
          echo "Using BUILD_DIR=$BUILD_DIR"

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ steps.prep.outputs.build_dir }}

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
