name: Deploy Angular to GitHub Pages

on:
  push:
    branches: [ main ]   # change if your default branch isn't "main"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - run: npm ci

      # Build with correct base href:
      # For a project site like https://<user>.github.io/<repo>/ keep the default below.
      # If your repo is <user>.github.io (user/organization site), change base-href to "/"
      - run: npm run build -- --configuration=production --base-href=/${{ github.event.repository.name }}/

      # Make SPA refresh work on Pages by serving 404.html as index.html
      - id: prep
        run: |
          BUILD_DIR=$(ls -d dist/* | head -n 1)
          cp "$BUILD_DIR/index.html" "$BUILD_DIR/404.html"
          echo "build_dir=$BUILD_DIR" >> $GITHUB_OUTPUT

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ steps.prep.outputs.build_dir }}

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
